config/routes.rb
Rails.application.routes.draw do
  resources :bootcamps
  root  'bootcamps#index'

end

app/models/bootcamp.rb
class Bootcamp < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bootcamps_controller.rb
class BootcampsController < ApplicationController
  before_action :set_bootcamp, only: [:show, :edit, :update, :destroy]

  # GET /bootcamps
  # GET /bootcamps.json
  def index
    @bootcamps = Bootcamp.all
  if params[:search].to_s != ''
    @bootcamps = Bootcamp.where("name LIKE '%#{params[:search]}%'")
  else
    @bootcamps = Bootcamp.all
  end
  end

  # GET /bootcamps/1
  # GET /bootcamps/1.json
  def show
  end

  # GET /bootcamps/new
  def new
    @bootcamp = Bootcamp.new
  end

  # GET /bootcamps/1/edit
  def edit
  end

  # POST /bootcamps
  # POST /bootcamps.json
  def create
    @bootcamp = Bootcamp.new(bootcamp_params)

    respond_to do |format|
      if @bootcamp.save
        format.html { redirect_to @bootcamp, notice: 'Bootcamp was successfully created.' }
        format.json { render :show, status: :created, location: @bootcamp }
      else
        format.html { render :new }
        format.json { render json: @bootcamp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bootcamps/1
  # PATCH/PUT /bootcamps/1.json
  def update
    respond_to do |format|
      if @bootcamp.update(bootcamp_params)
        format.html { redirect_to @bootcamp, notice: 'Bootcamp was successfully updated.' }
        format.json { render :show, status: :ok, location: @bootcamp }
      else
        format.html { render :edit }
        format.json { render json: @bootcamp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bootcamps/1
  # DELETE /bootcamps/1.json
  def destroy
    @bootcamp.destroy
    respond_to do |format|
      format.html { redirect_to bootcamps_url, notice: 'Bootcamp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bootcamp
      @bootcamp = Bootcamp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bootcamp_params
      params.require(:bootcamp).permit(:name, :description, :dates)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootcamps_helper.rb
module BootcampsHelper
end

app/views/bootcamps/_form.html.erb
<%= form_for(@bootcamp) do |f| %>
  <% if @bootcamp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bootcamp.errors.count, "error") %> prohibited this bootcamp from being saved:</h2>

      <ul>
      <% @bootcamp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :dates %><br>
    <%= f.text_field :dates %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bootcamps/edit.html.erb
<h1>Editing Bootcamp</h1>

<%= render 'form' %>

<%= link_to 'Show', @bootcamp %> |
<%= link_to 'Back', bootcamps_path %>

app/views/bootcamps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Search</h1>
<%= form_tag(bootcamps_path, method: "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Bootcamps" %>
  <%= submit_tag "Search Bootcamps"%>
<% end %>

<h1>Listing Bootcamps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Dates</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bootcamps.each do |bootcamp| %>
      <tr>
        <td><%= bootcamp.name %></td>
        <td><%= bootcamp.description %></td>
        <td><%= bootcamp.dates %></td>
        <td><%= link_to 'Show', bootcamp %></td>
        <td><%= link_to 'Edit', edit_bootcamp_path(bootcamp) %></td>
        <td><%= link_to 'Destroy', bootcamp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bootcamp', new_bootcamp_path %>

app/views/bootcamps/new.html.erb
<h1>New Bootcamp</h1>

<%= render 'form' %>

<%= link_to 'Back', bootcamps_path %>

app/views/bootcamps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bootcamp.name %>
</p>

<p>
  <strong>Description:</strong>
  <%=raw @bootcamp.description %>
</p>

<p>
  <strong>Dates:</strong>
  <%= @bootcamp.dates %>
</p>

<%= link_to 'Edit', edit_bootcamp_path(@bootcamp) %> |
<%= link_to 'Back', bootcamps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>